version: '3'
services:
  backend:
    depends_on:
      - postgres
    container_name: tai_api
    image: lucasgitdev/tai_api:latest
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - ./.env:/usr/src/app/.env:ro
    networks:
      - proxy_manager

  postgres:
    image: postgres:15.1
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}_${NODE_ENV}
    restart: always
    networks:
      - proxy_manager
      
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxymanager
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - proxy_manager

networks:
  proxy_manager:
    name: proxy_manager

